using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Forma.Domain.Entities.ExerciseAggregate;
using Forma.Domain.Entities.ExerciseAggregate.ValueObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Forma.Infrastructure.Data.Mappings;

internal class ExerciseResourceConfiguration : IEntityTypeConfiguration<ExerciseResource>
{
    public void Configure(EntityTypeBuilder<ExerciseResource> builder)
    {
        // Sets the primary key for the entity to the Id property.
        builder
            .HasKey(entity => entity.Id);

        // Configures the Id property to be required (NOT NULL) and not generated by the database.
        builder
            .Property(entity => entity.Id)
            .HasConversion(e => e.Value, value => new(value))
            .IsRequired()
            .ValueGeneratedNever();
            //.Metadata.SetValueComparer(
            //                new ValueComparer<ExerciseResourceId>(
            //        (a, b) => a.Value == b.Value,
            //        v => v.Value.GetHashCode(),
            //        v => new ExerciseResourceId(v.Value))
            //);



        builder
            .Property(entity => entity.ExerciseId)
            .HasConversion(e => e.Value, value => new(value))
            .IsRequired()
            .ValueGeneratedNever();

        builder
            .Property(entity => entity.Title)
            .IsRequired()
            .HasMaxLength(100);

        builder.Property(entity => entity.Content)
            .HasMaxLength(1000);

        builder
            .Property(entity => entity.Type)
            .HasConversion<string>()
            .HasMaxLength(50)
            .IsRequired();

        builder
            .Property(entity => entity.Link)
            .IsRequired()
            .HasMaxLength(400);

        builder
            .HasIndex(entity => new { entity.ExerciseId, entity.Id })
            .IsUnique()
            .HasDatabaseName("UQ_ExerciseResource_ExerciseId_ExerciseResourceId");

        builder
            .HasIndex(entity => entity.Link)
            .IsUnique()
            .HasDatabaseName("UQ_ExerciseResource_Link");

    }
}


